### ISSUE TITLE
Https example ?

### ISSUE THREAD

**Issue by src386** [bbruun/k3s-getting-started#3]
k3s comes with traefik acting as a the main LB. It's fairly easy to route trafik to http protocol, but I can't figure out how does it works with https. If you managed to make it work, an extended example with https would be appreciated :)

**Comment by bbruun** [comment]
Hi
I'm very very sorry that I've not seen this issue before now, it must have gotten lost in my busy life.

HTTPS is a whole setup on the side using https://cert-manager.io and then creating certificates that way that can be added to the ingress manifest under `rules` eg

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotation:
    cert-manager.io/cluster-issuer: aNameForTheCertManagerProviderYouSetup
spec:
  rules:
  - host: nginx.example.com
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80
        path:
  tls:
  - hosts:
    - nginx.example.com
    secretName: aSecretNameForTheIngress
```
But that requires, as stated, a whole lot of other work. 

The documentation for cert-manager.io is really good and it has examples for working with Lets Encrypt (both staging (for testing while you get it working) and production certificates which have a max per time requests you can issue).
